export const SEMANTIC_CLASSES = {
  /* ── Layout (ds.utilities) ── */
  page: "ui-page",
  pageMain: "ui-page-main",
  pageDashboard: "ui-page--dashboard",
  band: "ui-band",
  bandSurface: "ui-band--surface",
  themeScope: "ui-theme-scope",
  stickyTop: "ui-sticky-top",
  container: "ui-container",
  containerNarrow: "ui-container--narrow",
  containerWide: "ui-container--wide",
  containerXl: "ui-container--xl",
  containerFull: "ui-container--full",
  section: "ui-section",
  sectionSm: "ui-section--sm",
  sectionLg: "ui-section--lg",
  stack: "ui-stack",
  stackTight: "ui-stack--tight",
  stackCompact: "ui-stack--compact",
  stackLoose: "ui-stack--loose",
  stackSpacious: "ui-stack--spacious",
  row: "ui-row",
  rowBetween: "ui-row--between",
  rowCenter: "ui-row--center",
  rowEnd: "ui-row--end",
  rowNowrap: "ui-row--nowrap",
  grid: "ui-grid",
  grid2: "ui-grid--2",
  grid3: "ui-grid--3",
  grid4: "ui-grid--4",
  gridAuto: "ui-grid--auto",
  split: "ui-split",
  splitReverse: "ui-split--reverse",
  center: "ui-center",
  hero: "ui-hero",
  flex1: "ui-flex-1",
  minW0: "ui-min-w-0",

  /* ── Shell layouts (ds.layouts) ── */
  footerGrid: "ui-footer-grid",
  footerLinks: "ui-footer-links",
  sidebar: "ui-sidebar",
  rightbar: "ui-rightbar",
  sidebarNav: "ui-sidebar-nav",
  sidebarNavTitle: "ui-sidebar-nav__title",
  shellGridLeft: "ui-shell-grid--left",
  shellGridRight: "ui-shell-grid--right",
  shellGridBoth: "ui-shell-grid--both",
  search: "ui-search",
  headerPad: "ui-header-pad",

  /* ── Typography (ds.utilities) ── */
  display1: "text-display-1",
  display2: "text-display-2",
  display3: "text-display-3",
  heading1: "text-heading-1",
  heading2: "text-heading-2",
  heading3: "text-heading-3",
  heading4: "text-heading-4",
  heading5: "text-heading-5",
  heading6: "text-heading-6",
  body: "text-body",
  bodyLarge: "text-body-large",
  bodySmall: "text-body-small",
  label: "text-label",
  caption: "text-caption",
  micro: "text-micro",
  overline: "text-overline",
  quote: "text-quote",
  code: "text-code",
  kbd: "text-kbd",
  kicker: "ui-kicker",
  lede: "ui-lede",

  /* ── Text color ── */
  textMuted: "text-muted",
  textAccent: "text-accent",
  textSuccess: "text-success",
  textWarning: "text-warning",
  textDanger: "text-danger",
  textInfo: "text-info",
  textInherit: "text-inherit",
  textOnPrimary: "text-on-primary",

  /* ── Prose ── */
  prose: "prose",
  proseSm: "prose-sm",
  proseLg: "prose-lg",
  proseXl: "prose-xl",

  /* ── Background color ── */
  bgSurface: "bg-surface",
  bgSurfaceElevated: "bg-surface-elevated",
  bgSurfaceSunken: "bg-surface-sunken",
  bgAccent: "bg-accent",
  bgSuccess: "bg-success",
  bgWarning: "bg-warning",
  bgDanger: "bg-danger",
  bgInfo: "bg-info",
  bgOverlay: "bg-overlay",

  /* ── Interactive states ── */
  focusRing: "ui-focus-ring",
  disabled: "ui-disabled",
  loading: "ui-loading",
  skipLink: "ui-skip-link",
  touchTarget: "ui-touch-target",

  /* ── Accessibility ── */
  srOnly: "sr-only",
  visuallyHidden: "ui-visually-hidden",
  livePolite: "ui-live-polite",
  liveAssertive: "ui-live-assertive",

  /* ── Responsive visibility ── */
  onlyMobile: "ui-only-mobile",
  onlyDesktop: "ui-only-desktop",
  onlyTablet: "ui-only-tablet",
  onlyMobileBlock: "ui-only-mobile-block",
  onlyDesktopBlock: "ui-only-desktop-block",
  containerQuery: "ui-container-query",

  /* ── Elevation ── */
  shadowNone: "shadow-none",
  shadowXs: "shadow-xs",
  shadowSm: "shadow-sm",
  shadowMd: "shadow-md",
  shadowLg: "shadow-lg",
  shadowXl: "shadow-xl",
  shadow2xl: "shadow-2xl",
  shadowInner: "shadow-inner",
  glass: "glass",

  /* ── Border / Radius ── */
  border: "border",
  borderT: "border-t",
  borderB: "border-b",
  roundedNone: "rounded-none",
  roundedSm: "rounded-sm",
  rounded: "rounded",
  roundedMd: "rounded-md",
  roundedLg: "rounded-lg",
  roundedFull: "rounded-full",
  divider: "ui-divider",
  dividerVertical: "ui-divider--vertical",

  /* ── Motion ── */
  transitionColors: "transition-colors",
  transitionTransform: "transition-transform",
  transitionOpacity: "transition-opacity",
  transitionAll: "transition-all",
  animateFadeIn: "animate-fade-in",
  animateSlideUp: "animate-slide-up",
  animateSlideDown: "animate-slide-down",
  animateScaleIn: "animate-scale-in",
  animateSpin: "animate-spin",
  animatePulse: "animate-pulse",
} as const;

export type SemanticClassKey = keyof typeof SEMANTIC_CLASSES;
export type SemanticClassName = (typeof SEMANTIC_CLASSES)[SemanticClassKey];

export function semanticClass(key: SemanticClassKey): SemanticClassName {
  return SEMANTIC_CLASSES[key];
}
