import type { Metadata } from "next";
import { Fira_Code, Inter, Montserrat } from "next/font/google";

import { ThemeInitScript } from "@/ds";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const display = Montserrat({
  variable: "--font-display",
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const mobilePresetScript = `(() => {
  const root = document.documentElement;
  const mq = window.matchMedia("(max-width: 48rem)");

  const apply = () => {
    if (mq.matches) {
      root.setAttribute("data-platform", "mobile");
      root.setAttribute("data-density", "compact");
      return;
    }
    root.removeAttribute("data-platform");
    root.removeAttribute("data-density");
  };

  apply();

  if (typeof mq.addEventListener === "function") {
    mq.addEventListener("change", apply);
  } else if (typeof mq.addListener === "function") {
    mq.addListener(apply);
  }
})();`;

  return (
    <html lang="en" className={`${inter.variable} ${display.variable} ${firaCode.variable}`} suppressHydrationWarning>
      <head>
        <ThemeInitScript />
        <script dangerouslySetInnerHTML={{ __html: mobilePresetScript }} />
      </head>
      <body>
        <a className="ui-skip-link" href="#main">
          Skip to content
        </a>
        {children}
      </body>
    </html>
  );
}
