import type { Metadata, Viewport } from "next";
import { Fira_Code, Inter, Montserrat } from "next/font/google";

import { ThemeInitScript, app } from "@/ds";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const display = Montserrat({
  variable: "--font-display",
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${display.variable} ${firaCode.variable}`} suppressHydrationWarning>
      <head>
        <ThemeInitScript />
        <app.PlatformPresetScript />
      </head>
      <body>
        <a className="ui-skip-link" href="#main">
          Skip to content
        </a>
        {children}
      </body>
    </html>
  );
}
