import type { Metadata } from "next";
import { Fira_Code, Inter, Montserrat } from "next/font/google";

import { ThemeInitScript } from "@/ds";
import "./globals.css";

import { PublicBottomNavGate } from "./_components/PublicBottomNavGate";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const display = Montserrat({
  variable: "--font-display",
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`theme-dark ${inter.variable} ${display.variable} ${firaCode.variable}`}>
      <body>
        <ThemeInitScript />
        <a className="ui-skip-link" href="#main">
          Skip to content
        </a>
        {children}
        <PublicBottomNavGate />
      </body>
    </html>
  );
}
